version: '3.8'

services:
  web:
    build: .
    container_name: taskmgr
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: taskmgrdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
